waza:
  slack:
    channel: "#bot-testing"
    token: <%= ENV['SLACK_TOKEN'] %>
  github:
    token: <%= ENV['GITHUB_TOKEN'] %>
    repos:
      waza_0:
        id: "en-japan/waza"
        approval: quorum
        commiters:
          mediavrog: maik.vlcek
          le-doude: edouard.pelosi
          pcboy: david.hagege
          shawila: salah.hawila