slack:

github:
  repos:
    waza:
      id: "en-japan/waza"
      channel: "#waza-dev"
      approval: quorum
      commiters:
        mediavrog: maik.vlcek
        le-doude: edouard.pelosi
        pcboy: david.hagege
        shawila: salah.hawila
