slack:
  token: <%= ENV["SLACK_TOKEN"]>

github:
  token: <%= ENV["GITHUB_TOKEN"]>
  repos:
    waza:
      id: "en-japan/waza"
      channel: "#waza-dev"
      commiters:
        mediavrog: maik.vlcek
        le-doude: edouard.pelosi
        pcboy: david.hagege
        shawila: salah.hawila
